version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    parameters:
      branch:
        type: string
    steps:
      - run: |
          echo "args, branch: << parameters.branch >>"

workflows:
  main:
    # do not run when tag event
    when:
      not: << pipeline.git.tag >>
    jobs:
      - build:
          branch: <<#pipeline.git.branch>><<pipeline.git.branch>><</pipeline.git.branch>>
          # # ignore tags explicitly
          # filters:
          #   tags:
          #     ignore: /.*/
