version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.2-buster
    resource_class: small
    steps:
      - run: 
          name: Install cryptography
          command: |
            pip install cryptography>=2.3.0
